image: docker:19.03.12

services:
  - docker:19.03.12-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

build_image:
  script:
    - docker build server/ -t server
    - docker build client/ -t client
    #- run tests (when we add tests)
