image: docker:18

services:
  - docker:18-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs"

build_image:
  script:
    - docker build server/ -t server
    - docker build client/ -t client
    #- run tests (when we add tests)
