concurrent = 1
check_interval = 0

[[runners]]
  name = "#####"
  url = "#####"
  token = "#####"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:3.4"
    privileged = true
    disable_cache = false
    cache_dir = "cache"
    volumes = ["/home/gitlab-runner/.ivy2:/root/.ivy2:rw"]
  [runners.cache]

