version: "3.6"
services:
  client:
    container_name: 'client'
    build: client
    ports:
      - "3000:3000"
    volumes:
      - "client:/client"
    image: "client"
  db:
    image: mysql:8.0.24
    container_name: 'db'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 'pass'
       MYSQL_DATABASE: 'db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'pass'
    ports:
      - "3318:3306"
    volumes:
      - ./db/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./db/mysql/storage:/var/lib/mysql
  server:
    restart: always
    container_name: 'server'
    build: server
    ports:
      - "8080:8080"
    volumes:
      - "server:/server"
    image: "server"

volumes:
  server:
  client:
